spring:
  application:
    name: FromZero Web Application

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.acme.fromzeroapi.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: ${PORT:8080}

authorization:
  jwt:
    secret: WriteHereYourSecretStringForTokenSigningCredentials
    expiration:
      days: 7
